### ISSUE TITLE
Saving models and visualizing them in netron

### ISSUE THREAD

**Issue by pabloinigoblasco** [AppleHolic/source_separation#22]
I am trying to visualize the models in netron.
In order to do that I tried to save the model into the disk after loading from checkpoint.
```
    model = __load_model(model_name, pretrained_path)
    torch.save(model, "noise-filter.pth")
```
However, I get a pickle/serialization exception because of lambda usage inside modules:
```
Can't pickle local object 'SpectrogramUnet.__init__.<locals>.<lambda>'
```
Then I found a solution using the "dill" python package that is able to handle the lambda issues:

```
    model = __load_model(model_name, pretrained_path)
    torch.save(model, "noise-filter.pth",  pickle_module=dill)
    model = torch.load("noise-filter.pth" , pickle_module=dill)
```
After this, the model continues working and filtering properly the noise from some input (I think everything is correct). Nonetheless the model cannot still be open with netron.

![image](https://user-images.githubusercontent.com/13334595/86116674-1feee280-bace-11ea-9bbe-f556278b2c35.png)

Does anybody know what could be the issue?

PS: I also tried to export the model to onnx and visualize it in netron but I still get some errors.

**Comment by AppleHolic** [comment]
@pabloinigoblasco I checked out that the model has [lambda funcion 1](https://github.com/AppleHolic/source_separation/blob/6f755889654d7207fc89ba03a2f49d9ba92df8ea/source_separation/models.py#L60) and [lambda function 2](https://github.com/AppleHolic/source_separation/blob/6f755889654d7207fc89ba03a2f49d9ba92df8ea/source_separation/models.py#L69). It makes that the model cannot be pickled directly. I think you can fix that line to save the model, and then it can be pickled.

**Comment by AppleHolic** [comment]
issue close
