### ISSUE TITLE
Train using own dataset

### ISSUE THREAD

**Issue by dmadhitama** [AppleHolic/source_separation#23]
Hello. Could you please give me an example or explanation about how to train the model using my own dataset?
I have some clean, noise, and noisy audio. How to prepare those datasets to be trained in the model?
Thank you.

**Comment by AppleHolic** [comment]
First, If you don't want to fix code, you should make an pandas data frame object to handle Meta Information. 

I handled it as some classes ([Voice Bank Case Code](https://github.com/AppleHolic/pytorch_sound/blob/61493c10cbf1c6ba9c7ee1c35ce5133fdd4cfe00/pytorch_sound/data/meta/voice_bank.py#L13) ), As you can see, it needs json file (meta_path), and it has columns to handle dataset ([code](https://github.com/AppleHolic/pytorch_sound/blob/61493c10cbf1c6ba9c7ee1c35ce5133fdd4cfe00/pytorch_sound/data/meta/voice_bank.py#L32)). 

And, meta files are separated to three files and it needs to saved on same directory [code](https://github.com/AppleHolic/pytorch_sound/blob/61493c10cbf1c6ba9c7ee1c35ce5133fdd4cfe00/pytorch_sound/data/meta/voice_bank.py#L18). 

If you complete to prepare your own data to fit on above process, you can use meta-directory on train.py.

---
