### ISSUE TITLE
Comparison with other repos

### ISSUE THREAD

**Issue by DonaldTsang** [AppleHolic/source_separation#24]
This repo is mainly for musical speech while https://github.com/speechLabBcCuny/onssen is for speaker clarity, correct?
If not, what would be the differences?

**Comment by AppleHolic** [comment]
Your question is either correct or not. This repository is started to remove background sounds in normal case([voice bank](https://datashare.is.ed.ac.uk/handle/10283/2651
)). But I think that it can be used on musical vocal cases, that function is added after first experiment ([dsd100](https://sigsep.github.io/datasets/dsd100.html)). So, this repository has two functions and you can pick a function for solving your case.

**Comment by AppleHolic** [comment]
If you have more questions, open another issue or comment on this issue. Close it.
