### ISSUE TITLE
Difference between model checkpoints

### ISSUE THREAD

**Issue by roudimit** [AppleHolic/source_separation#25]
Hi, 

Thank you for this great project and for uploading the model weights!

What is the difference between first_voice_bank.best.chkpt and second_voice_bank.best.chkpt in the Google Drive folder for 'General Voice Source Separation'?

These checkpoints are from the training with Audioset data augmentation, right?

**Comment by AppleHolic** [comment]
Yes those are trained with data augmentation. And, second one gets more training time and better result. I recommend using second one.

**Comment by AppleHolic** [comment]
Close this issue
