### ISSUE TITLE
Parameter mismatch while loading model 

### ISSUE THREAD

**Issue by gulzainali98** [AppleHolic/source_separation#26]
I am getting error while loading the model voice bank joint. 
There seems to be a parameter mismtach. Not sure why that model exists. Please help! Here is a small snippet to give a better idea
`
"source_separation/synthesize.py", line 28, in __load_model                                                          model.load_state_dict(get_loadable_checkpoint(chk))                                                                   File "/data/Gul_Zain/visenti.ai/Source Separation/source_separation/sep-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict                                                                                self.__class__.__name__, "\n\t".join(error_msgs)))                                                                  RuntimeError: Error(s) in loading state_dict for RefineSpectrogramUnet:                                                         size mismatch for stft.square_window: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).                                                                                           size mismatch for stft.forward_basis: copying a param with shape torch.Size([1026, 1, 1024]) from checkpoint, the shape in current model is torch.Size([514, 1, 512]).`

Looking forward to response.

**Comment by AppleHolic** [comment]
Your downloaded checkpoint file seems to "larger" model, but you passes a model name of "base" model. Check out [this code](https://github.com/AppleHolic/source_separation/blob/6f755889654d7207fc89ba03a2f49d9ba92df8ea/source_separation/settings.py#L37) and passes "model_name" correctly.

**Comment by bmaneesh** [comment]
Hi, I have tested out different models from settings.py but none of the pretrained models present on the drive link match the model definitions on `synthesize.py test-dir` or `separate`. I also noticed that it could be because of the version of the codebase and there is no v0.0.0(for which the models are available on the drive) code. Could you suggest how we can test your pretrained models?

Thanks

**Comment by AppleHolic** [comment]
@bmaneesh 
Ah, I think I missed some updated contents of them. I will check and update later them..

In other way, recently, I distributed Colab Notebook to test that models, you can check out how to inference that models in command line. Check it and let me tell when some other problems are happened.

- link : [https://colab.research.google.com/github/Appleholic/source_separation/blob/master/assets/Source_Separation_first_notebook.ipynb](https://colab.research.google.com/github/Appleholic/source_separation/blob/master/assets/Source_Separation_first_notebook.ipynb)
![image](https://user-images.githubusercontent.com/3727290/102994216-ffc24c80-4561-11eb-97d5-87074ba63ffd.png)
