### ISSUE TITLE
Separate Noise File 

### ISSUE THREAD

**Issue by HaseebYounis1** [AppleHolic/source_separation#32]
This is very good work. How can I get a noise file that is separated from the original file? There is only one clean file in the result. Thanks

**Comment by AppleHolic** [comment]
Unfortunately, this repository is trained for separating speech and vocal only. Simple cases can be calculated by subtracting predicted audio with original audio, it is not guaranteed.

**Comment by AppleHolic** [comment]
Close this issue.
