### ISSUE TITLE
Want to Contribute to this amazing Project

### ISSUE THREAD

**Issue by Navaneeth-Sharma** [AppleHolic/source_separation#33]
Hi, 
The Documentation of this project is very well maintained, thanks a lot. But I found some improvements as a beginner to this field. Can I make a pull request on this?
I have experience of making Pypi packages. Can I try to contribute to this project via making it as a Pypi package ? So that the installation will be much simpler. 

Thank you

**Comment by AppleHolic** [comment]
I am not maintaining any more from a year ago, and maybe I will archive this repository soon. But If you wanna add inference sources with pypi, I will check your PR.

**Comment by AppleHolic** [comment]
I'm closing it now. If you wanna make a PR, I will check that request.

**Comment by Navaneeth-Sharma** [comment]
Hi ,
Ohk,Thank you for the reply and information.
