### ISSUE TITLE
what is the value of the  parameter--pretrained_path?

### ISSUE THREAD

**Issue by DaerTaeKook** [AppleHolic/source_separation#7]
I am so sorry to disturb you. When I try to run the train.py in source separation, .I do not know the value of the parameter--pretrained_path. I have run the project--pytorch_sound , But it did not s generate checkpoint files. May I ask what is the correct value of it ? Thank you for your help.

**Comment by AppleHolic** [comment]
@DaerTaeKook I missed handling 'save_prefix' exception cases to be not passed any prefix that you described. This parameter separates your experiments that has same model or parameter. 
And 'pretrained_path' is the file path of trained checkpoint. So, If you wanna more training after some training process is done, you can put the specific file path of checkpoint. 
At next update of this repository, I will describe what the parameter is.

**Comment by AppleHolic** [comment]
If you have more questions, and please contact me with email. You can check out address on my profile. Close it.
