### ISSUE TITLE
logstft vs. linear stft

### ISSUE THREAD

**Issue by faroit** [AppleHolic/source_separation#9]
Hi, this is a great implementation of the complex unet. Congrats. I wonder if why you chose to use the logstft instead of the linear stft as done [here](https://github.com/AppleHolic/source_separation/blob/179f7f9b8fef7050b99d03688794fea345971430/source_separation/models.py#L114). Did you observe better performance?

Just a small note, You have used MUSDB18 instead of DSD100 for singing voice. Its a bit larger. By the way, did you evaluate your results using museval?

Cheers
Fabian

**Comment by AppleHolic** [comment]
@faroit 

1. Linear stft has too large numbers for training model in stably. When I made first model, I got faced gradient explosion on using linear stft, so I thought simply to solve them using log space.

2. Not yet do that and thanks for awakening them. I will make a new model on MUSDB18 dataset and evaluate them with museval soon. 

I will follow up second issue and notice the progress on this issue.

Thanks!

**Comment by faroit** [comment]
> Linear stft has too large numbers for training model in stably. When I made first model, I got faced gradient explosion on using linear stft, so I thought simply to solve them using log space.

I see. Have you considered using mean/std normalization instead/additionally?

**Comment by AppleHolic** [comment]
No, I didn't consider using mean/std normalization. That also seems like can help the result. When I will have next experiment, I additionally  try that.

**Comment by AppleHolic** [comment]
On Testing, Simple comment
- Evaluation PESQ will be coded, reported
  - reference repo : https://github.com/ludlows/python-pesq
- validation score (it is resampled from 22.05k to 16k)
1. with audioset : 2.4
2. without audioset : 2.37

But, I got more better result on test data with audioset.

**Comment by AppleHolic** [comment]
Continues following issue on #16 and other, close it.
- Adding MUSDB
